name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100

    - name: Restore Grats.Api.Test
      run: |
        dotnet restore Grats.Api.Test/Gratify.Grats.Api.Test.csproj

    - name: Build Grats.Api.Test
      run: |
        dotnet build Grats.Api.Test/Gratify.Grats.Api.Test.csproj \
          --configuration Release \
          --no-restore

    - name: Test Grats.Api.Test
      run: |
        dotnet test Grats.Api.Test/Gratify.Grats.Api.Test.csproj \
          --configuration Release \
          --no-build

    - name: Publish Grats.Api
      run: |
        dotnet publish Grats.Api/Gratify.Grats.Api.csproj \
          --output ${{env.DOTNET_ROOT}}/app \
          --configuration Release \
          --no-build

    - name: 'Deploy Grats.Api to Azure'
      uses: azure/webapps-deploy@v1
      with:
        app-name: grats-api
        publish-profile: ${{ secrets.GRATS_API_PUBLISH_PROFILE }}
        package: ${{ env.DOTNET_ROOT }}/app
